set -g mouse on
set -g set-clipboard on
set -g allow-passthrough on

# Uncomment this line if you have problems with Shift+arrows
# set -g default-terminal "xterm-256color"

set -g status-left-length 100

unbind -n WheelUpPane
unbind -n WheelDownPane

bind -n WheelUpPane if-shell -F '#{mouse_any_flag}' \
  'send-keys -M' \
  'if-shell -F "#{alternate_on}" "send-keys Up" "copy-mode -e"'

bind -n WheelDownPane if-shell -F '#{mouse_any_flag}' \
  'send-keys -M' \
  'if-shell -F "#{alternate_on}" "send-keys Down" ""'

bind h split-window -h
bind v split-window -v

bind -n C-M-Left  select-pane -L
bind -n C-M-Right select-pane -R
bind -n C-M-Up    select-pane -U
bind -n C-M-Down  select-pane -D

bind -n M-` select-pane -t :.+
bind -n M-~ select-pane -t :.-

bind -n F11 resize-pane -Z

bind q confirm-before -p "Kill current session? (y/n)" kill-session
